export const GET_COMPANIES = "GET_COMPANIES";
export const START_GET_COMPANIES = "START_GET_COMPANIES";
export const COMPLETE_GET_COMPANIES = "COMPLETE_GET_COMPANIES";
export const FAIL_GET_COMPANIES = "FAIL_GET_COMPANIES";

export const GET_ITEMS = "GET_ITEMS";
export const START_GET_ITEMS = "START_GET_ITEMS";
export const COMPLETE_GET_ITEMS = "COMPLETE_GET_ITEMS";
export const FAIL_GET_ITEMS = "FAIL_GET_ITEMS";
