export const GET_COMPANIES = "GET_COMPANIES";
export const START_GET_COMPANIES = "START_GET_COMPANIES";
export const COMPLETE_GET_COMPANIES = "COMPLETE_GET_COMPANIES";
export const FAIL_GET_COMPANIES = "FAIL_GET_COMPANIES";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const START_GET_PRODUCTS = "START_GET_PRODUCTS";
export const COMPLETE_GET_PRODUCTS = "COMPLETE_GET_PRODUCTS";
export const FAIL_GET_PRODUCTS = "FAIL_GET_PRODUCTS";

export const APPLY_FILTER = "APPLY_FILTER";
export const APPLY_SORT = "APPLY_SORT";

export const ADD_TO_CHART = "ADD_TO_CHART";
export const REMOVE_FROM_CHART = "REMOVE_FROM_CHART";

export const SHOW_BOTTOM_SHEET = "SHOW_BOTTOM_SHEET";
export const CLOSE_BOTTOM_SHEET = "CLOSE_BOTTOM_SHEET";
